repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args:
          - --fix=lf
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.1
    hooks:
      - id: ruff-format
      - id: ruff-check
        args: [--fix]

  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v9.2.0
    hooks:
      - id: cspell
        pass_filenames: false
        args:
          - --unique
          - --no-progress
          - --no-summary
          - --show-suggestions
          - --no-cache
          - --dot
          - --gitignore
          - --validate-directives
          - "."

  - repo: local
    hooks:
      - id: pyright
        language: system
        name: pyright
        entry: uv run --all-extras pyright
        args:
          - --threads
          - "4"
          - .
        pass_filenames: false
