"""add cookie

Revision ID: d017ee4f7c57
Revises:
Create Date: 2025-08-20 20:46:54.700592

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d017ee4f7c57"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cookie",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("value", sa.String(), nullable=False),
        sa.Column("domain", sa.String(), nullable=False),
        sa.Column("path", sa.String(), nullable=False),
        sa.Column("expires", sa.Numeric(), nullable=True),
        sa.Column("http_only", sa.Boolean(), nullable=True),
        sa.Column("secure", sa.Boolean(), nullable=True),
        sa.Column(
            "same_site",
            sa.Enum("Lax", "None", "Strict", native_enum=False),
            nullable=True,
        ),
        sa.Column("partition_key", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("name", "domain", "path"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cookie")
    # ### end Alembic commands ###
