"""init

Revision ID: d2c0bf6b2fb3
Revises:
Create Date: 2025-09-02 17:14:32.404400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2c0bf6b2fb3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cookie',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('expires', sa.Numeric(), nullable=True),
    sa.Column('http_only', sa.Boolean(), nullable=True),
    sa.Column('secure', sa.Boolean(), nullable=True),
    sa.Column('same_site', sa.Enum('Lax', 'None', 'Strict', native_enum=False), nullable=True),
    sa.Column('partition_key', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('name', 'domain', 'path')
    )
    op.create_table('job_detail',
    sa.Column('company_encrypt_brand_id', sa.String(), nullable=False, comment='公司-id'),
    sa.Column('company_brand_name', sa.String(), nullable=False, comment='公司-名称, eg: 字节跳动'),
    sa.Column('company_stage_name', sa.String(), nullable=False, comment='公司-融资阶段, eg: 已上市'),
    sa.Column('company_scale_name', sa.String(), nullable=False, comment='公司-规模, eg: 100-499人'),
    sa.Column('company_industry_name', sa.String(), nullable=False, comment='公司-行业分类, eg: 互联网'),
    sa.Column('company_introduce', sa.String(), nullable=False, comment='公司-介绍'),
    sa.Column('job_encrypt_id', sa.String(), nullable=False, comment='职位-id'),
    sa.Column('job_name', sa.String(), nullable=False, comment='职位-名称, eg: 高级python开发工程师'),
    sa.Column('job_city_name', sa.String(), nullable=False, comment='职位-工作地-城市, eg: 杭州'),
    sa.Column('job_area_district', sa.String(), nullable=False, comment='职位-工作地-区域, eg: 西湖区'),
    sa.Column('job_business_district', sa.String(), nullable=False, comment='职位-工作地-商圈, eg: 西溪'),
    sa.Column('job_address', sa.String(), nullable=False, comment='职位-工作地-详细地址'),
    sa.Column('job_experience_name', sa.String(), nullable=False, comment='职位-经验要求, eg: 5-10年'),
    sa.Column('job_degree', sa.String(), nullable=False, comment='职位-学历要求, eg: 本科'),
    sa.Column('job_salary_description', sa.String(), nullable=False, comment='职位-薪资待遇, eg: 12-24K'),
    sa.Column('job_description', sa.String(), nullable=False, comment='职位-职位详情'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('job_encrypt_id')
    )
    op.create_table('job_evaluation',
    sa.Column('job_encrypt_id', sa.String(), nullable=False),
    sa.Column('technology_match_score', sa.Numeric(), nullable=False, comment='技术匹配度-0~5分'),
    sa.Column('technology_match_reason', sa.String(), nullable=False, comment='技术匹配度-打分原因'),
    sa.Column('project_experience_match_score', sa.Numeric(), nullable=False, comment='项目经验匹配度-0~5分'),
    sa.Column('project_experience_match_reason', sa.String(), nullable=False, comment='项目经验匹配度-打分原因'),
    sa.Column('industry_experience_match_score', sa.Numeric(), nullable=False, comment='行业经验匹配度-0~5分'),
    sa.Column('industry_experience_match_reason', sa.String(), nullable=False, comment='行业经验匹配度-打分原因'),
    sa.Column('level_match_score', sa.Numeric(), nullable=False, comment='职级匹配度-0~5分'),
    sa.Column('level_match_reason', sa.String(), nullable=False, comment='职级匹配度-打分原因'),
    sa.Column('growth_potential_score', sa.Numeric(), nullable=False, comment='工作/管理潜力-0~5分'),
    sa.Column('growth_potential_reason', sa.String(), nullable=False, comment='工作/管理潜力-打分原因'),
    sa.Column('technical_depth_potential_score', sa.Numeric(), nullable=False, comment='技术潜力-0~5分'),
    sa.Column('technical_depth_potential_reason', sa.String(), nullable=False, comment='技术潜力-打分原因'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('job_encrypt_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_evaluation')
    op.drop_table('job_detail')
    op.drop_table('cookie')
    # ### end Alembic commands ###
