"""add job_detail.interested_at

Revision ID: f7a11a8bc1ea
Revises: d2c0bf6b2fb3
Create Date: 2025-09-04 18:24:54.381046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7a11a8bc1ea'
down_revision: Union[str, Sequence[str], None] = 'd2c0bf6b2fb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cookie', 'updated_at', new_column_name='last_updated_at')
    op.alter_column('job_detail', 'updated_at', new_column_name='last_updated_at')
    op.add_column('job_detail', sa.Column('interested_at', sa.DateTime(timezone=True), nullable=True, comment='标记为“感兴趣”的时间'))
    op.add_column('job_detail', sa.Column('last_applied_at', sa.DateTime(timezone=True), nullable=True, comment='最后一次申请的时间'))
    op.alter_column('job_evaluation', 'updated_at', new_column_name='last_updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_evaluation', 'last_updated_at', new_column_name='updated_at')
    op.alter_column('job_detail', 'last_updated_at', new_column_name='updated_at')
    op.drop_column('job_detail', 'last_applied_at')
    op.drop_column('job_detail', 'interested_at')
    op.alter_column('cookie', 'last_updated_at', new_column_name='updated_at')
    # ### end Alembic commands ###
